<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    function assert(expression, message) {
        if (!expression) {
            throw {name: 'Assertion Exception', message: message};
        }
    }
    assert(typeof  myVar != 'undefined', 'myVar is undefined!');

    console.assert(typeof myVar != 'undefined', 'myVar is undefined!');

    try {
        throw new Error('出错了!');
    } catch (e) {
        console.log(e.name + ": " + e.message);
        console.log(e.stack);
    }

    function throwIt(exception) {
        try  {
            throw exception;
        } catch (e) {
            console.log('Caught:' + e);
        }
    }

    throwIt(3);
    throwIt('hello');
    throwIt(new Error('An error happened'));


    var n = 100;
    try {
        throw n;
    } catch (e) {
        if (e <= 50) {

        } else {
            throw e;
        }
    }

    try {
        foo.bar();
    } catch (e) {
        if (e instanceof EvalError) {
            console.log(e.name + ": " + e.message);
        } else if (e instanceof RangeError) {
            console.log(e.name + ": " + e.message);
        }
    }


    function cleansUp() {
        try  {
            throw new Error('出错了.....');
            console.log('此行不会执行');
        } finally  {
            console.log('完成清理工作');
        }
    }

    cleansUp()


    function idle(x) {
        try {
            console.log(x);
            return 'result';
        } finally  {
            console.log("Finally");
        }
    }

    idle('hello');
</script>
</body>
</html>